package com.challenge.qube;
import java.util.*;
import java.io.*;
public class Initializer {
	
	public static Map<String, Boolean> getIsRegionAuthorizedMap() {
		Map<String, Boolean> isRegionAuthorized = new HashMap<>();
		
		try (InputStream is = Initializer.class.getResourceAsStream("cities.csv");
	             BufferedReader br = new BufferedReader(new InputStreamReader(is))) {
            String line;
            line = br.readLine();
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length >= 3) {
                    String key = parts[0].trim() + "," + parts[1].trim() + "," + parts[2].trim(); // Key is generated by concatenating the cityCode, stateCode and countryCode
                    isRegionAuthorized.put(key, false);  // By default, all regions in the map are marked false(unauthorized) 
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
		
		return isRegionAuthorized;
	}
}
